### ISSUE TITLE
Extension Data for AC

### ISSUE THREAD

**Issue by apoapostolov** [ElfFriend-DnD/foundryvtt-dnd5eExtender#8]
The ability to define additional Defensive Stats such as DR (Damage Reduction), Touch AC, etc. and display them in a pop-up field from the AC location. These additional AC types can be AC (to hit) or DR (damage reduction).

**Comment by akrigline** [comment]
Thanks for the submission!
Would these be expected to affect anything else on the sheet/actor?

What is the "use case" for these extra attributes?

Is there a 'list' of these or should they be arbitrary?
